apiVersion: v1
kind: ConfigMap
metadata:
  name: urlshortener-config
data:
  application.properties: |
    application.title=url-sortener
    expanded.project.version=@project.version@
  
    spring.application.name=urlshortener

    server.port=8887
    server.servlet.context-path=/v1/api/urlshortener

    spring.data.mongodb.uri=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo-dev:27017
    spring.data.mongodb.database=SOAP

    nasa-client.url=https://www.nasa.gov/news-release/feed/
    nasa-client.cron=*/5 * * * * *
